import { AWARD_EDITIONS } from './data';
import { musicHref, safeUrl } from './model';
import type { AwardEdition, AwardEntry } from './model';
import { tr, trName, trResult, trCategory, trScope, trEdition, trSource, isJa } from './i18n';
export const escapeHtml = (v: string | number) => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const esc = escapeHtml;
export const EVENT_ORDER = ['mama-2025','kma-2026','maj-2026','golden-disc-2026','mma-2025','record-awards-2025','kohaku-2025'];
const labels: Record<string,string> = {mama:'MAMA',kma:'한국대중음악상',maj:'MUSIC AWARDS JAPAN','golden-disc':'GOLDEN DISC',mma:'MMA','record-awards':'日本レコード大賞',kohaku:'NHK 紅白歌合戦'};
export const findEdition = (id: string) => AWARD_EDITIONS.find(e => e.id === id)!;
const asset = (file: string, alt: string, cls = '') => `<span class="ha-image ${cls}"><img src="/awards/${esc(file)}" alt="${esc(alt)}" decoding="async" loading="lazy"><span class="ha-image-fallback" hidden>${esc(alt)} · ${esc(tr('이미지 제공 안 됨'))}</span></span>`;
const meta = (e: AwardEdition) => `<p class="ha-date">${esc(trEdition(e.edition || String(e.year)))} · <time datetime="${esc(e.date)}">${esc(e.date.replaceAll('-','.'))}</time>${e.endDate ? '–'+esc(e.endDate.slice(8)):''}</p>`;
let curSeries = '';
const cat = (r: AwardEntry) => trCategory(curSeries, r.category);
const song = (r: AwardEntry) => `<a href="${esc(musicHref(r))}">${esc(r.recipient)}${r.work ? ' · '+esc(r.work):''}<span aria-hidden="true"> ↗</span></a>`;
function lead(e: AwardEdition, index = 0) { const r=e.entries[index]; return `<div class="ha-lead"><p>${esc(cat(r))}</p><strong>${esc(r.recipient)}</strong>${r.work?`<span>${esc(r.work)}</span>`:''}<a class="ha-search" href="${esc(musicHref(r))}">${esc(tr('음악 검색'))} ↗</a></div>`; }
/** Each edition owns its composition, not a theme on a shared hero-card template. */
export function brandStage(e: AwardEdition): string {
  curSeries = e.series;
  switch(e.series) {
    case 'mama': return `<div class="ha-mama">${asset('mama-2025-tiger-keyvisual.jpg','2025 MAMA AWARDS, 블랙 타이거 공식 키 비주얼','ha-tiger')}<div class="ha-mama-caption">${meta(e)}<h3>2025 MAMA AWARDS</h3><div class="ha-mama-winners">${e.entries.slice(0,4).map(r=>`<div><span>${esc(cat(r))}</span>${song(r)}</div>`).join('')}</div></div></div>`;
    case 'kma': return `<div class="ha-kma"><div class="ha-kma-masthead">${asset('kma-2026-organizer-logo.svg','한국대중음악상 공식 로고')}<span>2026 / 23</span></div><div class="ha-kma-split"><div class="ha-kma-scene"><span aria-hidden="true">2026</span>${asset('kma-2026-home-stage.jpg','제23회 한국대중음악상 공식 무대, 디더 이미지')}</div><div class="ha-kma-editorial">${meta(e)}<h3>${isJa() ? '韓国大衆<br>音楽賞' : '한국대중<br>음악상'}</h3>${lead(e,2)}<p class="ha-kma-index">KOREAN MUSIC AWARDS<br>2026</p></div></div></div>`;
    case 'maj': return `<div class="ha-maj"><div class="ha-maj-masthead">${asset('maj-2026-logo.png','MUSIC AWARDS JAPAN 2026 공식 로고')}<div>${meta(e)}<h3>受賞作品 / アーティスト</h3></div></div>${asset('maj-2026-awards-hero.jpg','MUSIC AWARDS JAPAN 2026 ALL AWARDS 트로피 배너','ha-wide-wordmark')}<div class="ha-maj-bottom"><span>主要6部門${isJa() ? '' : '<br>주요 6개 부문'}</span>${lead(e)}</div></div>`;
    case 'golden-disc': return `<div class="ha-golden">${asset('golden-disc-2026-keyvisual.jpg','제40회 골든디스크어워즈 공식 인디고 배경','ha-golden-bg')}<div class="ha-golden-front">${meta(e)}${asset('golden-disc-2026-title.svg','제40회 GOLDEN DISC AWARDS 공식 타이틀','ha-golden-title')}<h3 class="ha-sr">${esc(trName('골든디스크어워즈'))} 2026</h3><div class="ha-golden-winners">${e.entries.slice(0,3).map(r=>`<div><span>${esc(cat(r))}</span>${song(r)}</div>`).join('')}</div></div></div>`;
    case 'mma': return `<div class="ha-mma"><div class="ha-mma-art">${asset('mma-2025-keyvisual.png','MMA 2025 핑크와 옐로 패싯 선물 공식 키 비주얼','ha-mma-gift')}${asset('mma-2025-hero-logo.png','MMA 2025 THE 17th MELON MUSIC AWARDS 공식 로고','ha-mma-logo')}</div><div class="ha-mma-footer"><div>${meta(e)}<h3>MELON MUSIC AWARDS</h3></div>${lead(e)}</div></div>`;
    case 'record-awards': return `<div class="ha-record"><div class="ha-record-heading"><h3>輝く！日本レコード大賞</h3>${meta(e)}</div>${asset('record-awards-2025-keyvisual.jpg','제67회 일본 레코드대상 TBS 공식 진행자 키 비주얼','ha-record-visual')}<div class="ha-record-result">${lead(e)}<p>第67回<br>2025</p></div></div>`;
    case 'kohaku': return `<div class="ha-kohaku"><div class="ha-kohaku-top"><span>第76回 NHK</span>${meta(e)}</div><h3 lang="ja"><span>紅</span><span>白</span><small>歌合戦</small></h3><div class="ha-kohaku-bottom"><div><p>2025.12.31</p><strong>${esc(trResult(e.result || ''))}</strong><p>${esc(tr('출연곡 기록'))}</p></div><div><p>${e.entries.map(r=>esc(r.recipient)).join(' / ')}</p><a href="https://www.nhk.or.jp/kouhaku/index.html" target="_blank" rel="noopener noreferrer">${esc(tr('공식 비주얼은 NHK에서'))} ↗</a></div></div></div>`;
    default: return `<h3>${esc(e.name)} ${esc(e.year)}</h3>`;
  }
}
const officialPages: Record<string,string>={mama:'https://mama.mnetplus.world/',kma:'https://koreanmusicawards.com/',maj:'https://www.musicawardsjapan.com/','golden-disc':'https://www.goldendisc.co.kr/ko',mma:'https://www.melon.com/mma/info.htm','record-awards':'https://www.tbs.co.jp/recordaward/',kohaku:'https://www.nhk.or.jp/kouhaku/index.html'};
export function panelHtml(e: AwardEdition, opened: ReadonlySet<string>): string {
  curSeries = e.series;
  const link=(url:string,label:string)=>`<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
  return `<div class="ha-panel ha-${esc(e.series)}-panel" id="ha-panel-${esc(e.id)}" role="tabpanel" aria-labelledby="ha-tab-${esc(e.id)}" tabindex="0">${brandStage(e)}<div class="ha-records"><details data-ha-detail="records"${opened.has(e.id+':records')?' open':''}><summary>${esc(tr(e.kind==='broadcast'?'출연곡':'주요 수상 기록'))} <span>${e.entries.length}</span></summary><p>${esc(trScope(e.series,e.scope))}</p>${e.result?`<p>${esc(trResult(e.result))}</p>`:''}<ol>${e.entries.map(r=>`<li><span>${esc(cat(r))}</span><div>${song(r)}${(r.searchTerms||[]).length>1?`<div class="ha-alternative-search">${r.searchTerms!.map(q=>`<a href="${esc(musicHref(r,q))}">${esc(q)}${isJa() ? '' : ' '}${esc(tr('검색'))} ↗</a>`).join('')}</div>`:''}</div>${link(e.sources.find(s=>s.id===r.sourceId)!.url,tr('근거'))}</li>`).join('')}</ol></details><details class="use-source" data-ha-detail="sources"${opened.has(e.id+':sources')?' open':''}><summary>${esc(tr('출처 · 이미지 이용 안내'))}</summary><ul>${e.sources.map(s=>`<li>${link(s.url,trSource(s.label))} <small>${esc(tr(s.kind==='report'?'보도':'공식'))} · ${esc(tr('확인'))} ${esc(s.checkedAt)}</small></li>`).join('')}</ul><p>${link(officialPages[e.series],tr('공식 디자인 참고 원본'))} · ${esc(tr(e.series==='kohaku'?'NHK 이미지 복제 금지에 따라 공식 이미지를 사용하지 않은 자체 문자 구성입니다.':'공식 레퍼런스 이미지를 사용한 로컬 프로토타입입니다. 저작권은 각 권리자에게 있으며, 게시·재배포 허락은 확인되지 않았습니다.'))}</p><p>${esc(tr('공개 배포 전 이미지와 상표 이용 허락을 확인해야 합니다.'))} <a href="/awards/asset-provenance.json" target="_blank" rel="noopener noreferrer">${esc(tr('파일별 원본·권리 기록'))} ↗</a></p></details></div></div>`;
}
export function sectionHtml(selected:string, opened:ReadonlySet<string>): string {return `<section class="home-awards" id="homeAwards" aria-labelledby="ha-heading"><header class="ha-heading"><h2 id="ha-heading">${esc(tr('음악상 · 연말무대'))}</h2><span>2025 / 2026</span></header><div class="ha-tabs" role="tablist" aria-label="${esc(tr('시상식과 연말 무대'))}" aria-orientation="horizontal">${EVENT_ORDER.map(id=>{const e=findEdition(id);return `<button type="button" role="tab" id="ha-tab-${id}" data-ha-tab="${id}" aria-controls="ha-panel-${id}" aria-selected="${id===selected}" tabindex="${id===selected?'0':'-1'}">${esc(e.series==='kma'?trName(labels[e.series]):labels[e.series])} <small>${e.year}</small></button>`;}).join('')}</div><div data-ha-stage>${EVENT_ORDER.map(id=>id===selected?panelHtml(findEdition(id),opened):`<div id="ha-panel-${id}" role="tabpanel" aria-labelledby="ha-tab-${id}" hidden></div>`).join('')}</div></section>`;}
